### ISSUE TITLE
To-do list for HW1 Problem4

### ISSUE THREAD

**Issue by JiaweiZhuang** [iacs-ac290r-2019-2/homework#1]
Maybe it is easier to track things here?

- [x] Use local view to construct the K matrix @davpineiro 
- [x] Compute the RHS vector F @yiqixie94 
- [ ] Test different `f(x)` and boundary conditions, compare with analytical solution
- [ ] Make plots and add description to Latex

**Comment by yiqixie94** [comment]
I finished the local integral for (N * N) and (partial N * partial N) as well as their global assembly. Then I realized that K and F are just one step away, and they better be constructed together. So @davpineiro sorry I had your part of work finished on the way. 

I believe we have now arrived at the complete solution. I tried the 3 tests in the homework statement - all of them passed. Please double check, and update any possible bugs in the code. 

Cheers

**Comment by JiaweiZhuang** [comment]
Nice job @yiqixie94 ! 

@davpineiro then could you take on the plotting and Latex part?

**Comment by davpineiro** [comment]
Yeah, I'll work on the plots and the latex

**Comment by JiaweiZhuang** [comment]
All set
